version: "3.8"

services:
  app:
    container_name: imsamimalik
    image: imsamimalik-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
