name: Github Container push

"on":
    push:
        branches:
            - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBONTAINER }}

    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/imsamimalik/imsamimalik2.0:latest --label "org.opencontainers.image.source=https://github.com/imsamimalik/imsamimalik2.0"
        docker push ghcr.io/imsamimalik/imsamimalik2.0:latest
